apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  labels:
    app: karsajobs
    tier: database
spec:
  selector:
    app: karsajobs
    tier: database
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
