apiVersion: v1
kind: Service
metadata:
  name: karsajobs-service
  labels:
    app: karsajobs
    tier: backend
spec:
  selector:
    app: karsajobs
    tier: backend
  ports:
    - protocol: "TCP"
      port: 8000
      targetPort: 8000
      nodePort: 30007
  type: NodePort
