apiVersion: v1
kind: Service
metadata:
  name: karsajobs-service
  labels:
    app: karsajobs
    tier: backend
spec:
  selector:
    app: karsajobs
    tier: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30007
  type: NodePort
