apiVersion: v1
kind: Service
metadata:
  name: karsajobs-ui-service
  labels:
    app: karsajobs-ui
spec:
  selector:
    app: karsajobs-ui
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: NodePort
