apiVersion: v1
kind: Service
metadata:
  name: karsajobs-ui-service
  labels:
    app: karsajobs
    tier: frontend
spec:
  selector:
    app: karsajobs
    tier: frontend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: NodePort
